# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

#Trigger tells pipeline when to do a build. Right now it is on changes to the main branch
trigger:
- main

#Tells pipeline to build the app using a mac enviroment
pool:
  vmImage: 'macos-latest'

variables:
  system.debug: 'true'
  
steps:
#Checkout the code from the repo
- checkout: self
  persistCredentials: true
  clean: true

#Install node on the device that is building
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '18.16.0' # you can use your desired version here

#Install our package dependencies
- script: yarn install
  displayName: Install Dependencies

#Install Java 11 for our Android Build
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Gradle@2
  displayName: 'Build APK'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleRelease'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'my-upload-key.keystore'
- task: AndroidSigning@3
  displayName: 'Sign APK'
  inputs:
    apkFiles: '''$**\*.apk'''
    apksignerKeystoreFile: 'my-upload-key.keystore'
    apksignerKeystorePassword: 'password'
    apksignerKeystoreAlias: 'my-key-alias'
    apksignerKeyPassword: 'password'

- task: PublishBuildArtifacts@1
  displayName: 'Pusblish APK to artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Build'
    publishLocation: 'Container'