# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

#Trigger tells pipeline when to do a build. Right now it is on changes to the main branch
trigger:
- main

#Tells pipeline to build the app using a mac enviroment
pool:
  vmImage: 'macos-latest'

variables:
  system.debug: 'true'
  
steps:
#Checkout the code from the repo
- checkout: self
  persistCredentials: true
  clean: true

#Install Java 11 for our Android Build
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

#Install node on the device that is building
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '16.13.1' # you can use your desired version here

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)'
    Contents: '/node_modules'

#Deleting File which may be causing the "Unable to determine the current character" Error
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)'
    Contents: '/android/app/build'
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)'
    Contents: '/android/build'

#- task: DeleteFiles@1
#  inputs:
#    SourceFolder: '$(system.defaultWorkingDirectory)'
#    Contents: '/node_modules/@react-native-community/cli/build/config'

#Install our package dependencies
- script: npm install --legacy-peer-deps
  displayName: Install Dependencies

- task: Gradle@2
  displayName: 'Build APK'
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/android'
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'clean bundleRelease'
    
- script: |
    ls -R $(System.DefaultWorkingDirectory)
  displayName: 'List Directory Contents'
- task: PublishBuildArtifacts@1
  displayName: 'Pusblish APK to artifacts'
  inputs:
    PathtoPublish: '$(system.defaultWorkingDirectory)/android/app/build/outputs/bundle/release/'
    ArtifactName: 'Build'
    publishLocation: 'Container'